channels:
- conda-forge
dependencies:
- python=3.10.13
- pip<=25.1.1
- pip:
  - mlflow==2.12.1
  - numpy==1.24.4
  - pandas==2.1.4
  - psutil==5.9.7
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - xgboost==2.0.3
name: mlflow-env
