# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
      - id: isort
        language_version: python3.10

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a3
    hooks:
      - id: pylint
        language_version: python3.10

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pipenv run pylint
        language: system
        types: [python]
        args: [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--recursive=y"
        ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pipenv run pytest
        language: system
        pass_filenames: false
        always_run: true
