deploy:
  runs-on: ubuntu-latest
  needs: tf-plan
  steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Plan
      run: terraform plan
      id: tf-plan
      working-directory: Infrastructure/

    - name: Terraform Apply
      id: tf-apply
      if: ${{ steps.tf-plan.outcome }} == 'success'
      run: terraform apply -auto-approve
      working-directory: Infrastructure/

    - name: Get EC2 Public IP
      id: get-ip
      working-directory: Infrastructure/
      run: |
        echo "ec2_dns_ip=$(terraform output -raw ec2_dns_ip)" >> $GITHUB_OUTPUT

    - name: SSH setup
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ steps.get-ip.outputs.ec2_dns_ip }} << 'EOF'
          cd /home/ubuntu/diabetes_mlops
          chmod +x deploy.sh
          ./deploy.sh
        EOF
