name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_DEFAULT_REGION: 'eu-north-1'
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.18

      - name: Install dependencies
        run: pip install pipenv && pipenv install --dev

      - name: Setup Kaggle API credentials
        run: |
          mkdir -p ~/.config/kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.config/kaggle/kaggle.json
          chmod 600 ~/.config/kaggle/kaggle.json

      - name: Run formatting, linting and tests
        run: pipenv run make all

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
            terraform init -upgrade
            terraform validate
        working-directory: Infrastructure/

      - name: Show Terraform lock file
        run: cat Infrastructure/.terraform.lock.hcl

      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -var="mlops_key=${{ secrets.MLOPS_SSH_PUBLIC_KEY }}"
        working-directory: Infrastructure/

      - name: Terraform Apply
        if: ${{ steps.tf-plan.outcome == 'success' }}
        run: terraform apply -auto-approve -var="mlops_key=${{ secrets.MLOPS_SSH_PUBLIC_KEY }}"
        working-directory: Infrastructure/

      - name: Save EC2 SSH key
        run: |
            echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
            chmod 600 ec2-key.pem

      - name: Get EC2 Public IP
        id: get-ip
        working-directory: Infrastructure/
        run: echo "ec2_dns_ip=$(terraform output -raw ec2_dns_ip)" >> $GITHUB_OUTPUT

      - name: Get MLFLOW DB Endpoint
        id: get-mlflow-db-endpoint
        run: echo "mlflow_db_endpoint=$(terraform output -raw db_mlflow_endpoint)" >> $GITHUB_OUTPUT
        working-directory: Infrastructure/

      - name: Get AIRFLOW DB Endpoint
        id: get-airflow-db-endpoint
        run: echo "airflow_db_endpoint=$(terraform output -raw db_airflow_endpoint)" >> $GITHUB_OUTPUT
        working-directory: Infrastructure/

      - name: Get GRAFANA DB Endpoint
        id: get-grafana-db-endpoint
        run: echo "grafana_db_endpoint=$(terraform output -raw db_grafana_endpoint)" >> $GITHUB_OUTPUT
        working-directory: Infrastructure/

      - name: Update .env on EC2
        run: |
            ssh -i ec2-key.pem -o StrictHostKeyChecking=no ubuntu@${{ steps.get-ip.outputs.ec2_dns_ip }} << 'EOF'
            cd diabetes_mlops

            sed -i "s|^AWS_ACCESS_KEY_ID=.*|AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}|" .env
            sed -i "s|^AWS_SECRET_ACCESS_KEY=.*|AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}|" .env
            sed -i "s|^KAGGLE_USERNAME=.*|KAGGLE_USERNAME=${{ secrets.KAGGLE_USERNAME }}|" .env
            sed -i "s|^KAGGLE_KEY=.*|KAGGLE_KEY=${{ secrets.KAGGLE_KEY }}|" .env
            sed -i "s|^MLFLOW_DB_ENDPOINT=.*|MLFLOW_DB_ENDPOINT=${{ steps.get-mlflow-db-endpoint.outputs.mlflow_db_endpoint }}|" .env
            sed -i "s|^AIRFLOW_DB_ENDPOINT=.*|AIRFLOW_DB_ENDPOINT=${{ steps.get-airflow-db-endpoint.outputs.airflow_db_endpoint }}|" .env
            sed -i "s|^GRAFANA_DB_ENDPOINT=.*|GRAFANA_DB_ENDPOINT=${{ steps.get-grafana-db-endpoint.outputs.grafana_db_endpoint }}|" .env

            echo "--- Updated .env file ---"
            cat .env
            EOF
